### ISSUE TITLE
fetch issues

### ISSUE THREAD

**Issue by ArktinenSieni** [datascienceproject2019-codescoop/dsp2019-tool#6]

**Comment by ArktinenSieni** [comment]
How should this function? Endpoint? What shoud be in the request?

**Comment by TeemuKoivisto** [comment]
Well it could be a new endpoint since it might take a bit long to process all the issues, so the frontend can actually show the basic info as the issue data is loading.

But yeah basically it would just get repo's issue-index using its name/id and then paginate the result storing the result into a big blob of text with reactions and timestamps. And then it would just aggregate some stats, average time-to-live of issues and avg reactions / total reactions to all issues. We could the NLP later if we have time.

**Comment by ArktinenSieni** [comment]
Closing for now: Using Github API burns rapidly when looking at issues.
