### ISSUE TITLE
fix gh_api

### ISSUE THREAD

**Issue by ArktinenSieni** [datascienceproject2019-codescoop/dsp2019-tool#7]

**Comment by ArktinenSieni** [comment]
Probably of my unstable fiddling.

**Comment by TeemuKoivisto** [comment]
Basically what happened was, it gave me an error:
```
File "/Users/teemu/git_projects/codescoop/dsp2019-tool/backend/services/gh_api.py", line 101, in get_branch_index
    if branch['name'] == branch_name:
TypeError: string indices must be integers
```
Which I tried to fix but couldn't figure it out. So instead I just created a new service that used the old local test data and added if-else check for GITHUB_API_KEY env variable for deciding which service to use. So now it throws:
```
return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/teemu/git_projects/codescoop/dsp2019-tool/backend/app.py", line 81, in get_predicted_project
    repo_df = repo_df.where((pd.notnull(repo_df)), None)
AttributeError: 'dict' object has no attribute 'where'
```
Which I presume is due to `repos` variable of not being a similar list of things(dataframes?) as the one the local getter returns.

**Comment by ArktinenSieni** [comment]
I'll move to use the PyGithub instead to avoid most of the errors.
